.\" Copyright (c) 2017, Martin Kepplinger <martink@posteo.de>
.\"
.\" %%%LICENSE_START(GPLv2+_DOC_FULL)
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, see
.\" <http://www.gnu.org/licenses/>.
.\" %%%LICENSE_END
.\"
.TH TS_CLOSE 3  "" "" "tslib"
.SH NAME
ts_close \- close a touch screen input device
.SH SYNOPSIS
.nf
.B #include <tslib.h>
.sp
.BI "int ts_close(struct tsdev *" dev ");"
.sp
.fi

.SH DESCRIPTION
.BR ts_close ()
closes a touch screen input device opened by
.BR ts_open ()
, see ts_open (3)

.SH RETURN VALUE
Zero is returned on success. A negative value is returned in case of an error.

.SH SEE ALSO
.BR ts_open (3),
.BR ts_read (3),
.BR ts_config (3),
.BR ts.conf (5)
