.TH "TS_HARVEST" "1" "" "" "tslib"
.SH "NAME"
ts_harvest \- Harvest hundreds of raw touch screen coordinates.
.SH SYNOPSIS
.B ts_harvest
.SH "DESCRIPTION"
.PP
ts_harvest can be used to linearize non linear touch screens as found in the h2200 device. Touch screen coordinates are saved to
.I ts_harvest.out
.SH "SEE ALSO"
.PP
ts.conf (5),
ts_test (1),
ts_test_mt (1),
ts_calibrate (1)
